apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-5suk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-5suk
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-5suk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-5suk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-5suk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ctwv-tenant/rhtap-demo-app/hacbs-test-project-5suk@sha256:47a2c3ec251ee665194962a5c2678515c9ee89cae3b08f6c8b373345ddac5ef1
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
